//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class angcontr
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string MidName { get; set; }
        public string LastNmme { get; set; }
        public string FatherName { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string SecurityQuestion { get; set; }
        public Nullable<bool> checkboxTermsConditions { get; set; }
    }
}
